name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Prepare files
        run: |
          mkdir -p _site
          cp -r public/* _site/
          cp -r src _site/
        
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: _site
          
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
